project 'LottieAnimationDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottieAnimationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LottieAnimationDemo

  pod 'lottie-ios'
  
  target 'LottieAnimationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottieAnimationDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
